title: Iago R. G. Bonifacio Portfolio
email: your-email@example.com
description: >-
  Professional portfolio and resume site for Iago R. G. Bonifacio.
baseurl: "" # no subpath
url: "" # e.g., https://your-username.github.io/your-repo
twitter_username: iagobonifacio
github_username: iagobonifacio

# Build settings
theme: beautiful-jekyll
plugins:
  - jekyll-feed

# Custom CSS
sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: "Iago R. G. Bonifacio"

# Include custom CSS in assets
include:
  - assets/css/custom.css
